<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-MyOit_Portal-da13daca-5334-47eb-a367-ba2f23aeed06</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <Version>0.4.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9" />
    <PackageReference Include="Microsoft.Graph" Version="6.2.0" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.11.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.11.0" />
    <PackageReference Include="Radzen.Blazor" Version="11.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IotWelt.Common\IotWelt.Common.csproj" />
    <ProjectReference Include="..\IotWelt.ServiceDefaults\IotWelt.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
